print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/vivian/Documents/GitHub/Iat-445-final-project/445 project 3/Assets/models/Bed2.mb"`)
{		
	file -o "/Users/vivian/Documents/GitHub/Iat-445-final-project/445 project 3/Assets/models/Bed2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/vivian/Documents/GitHub/Iat-445-final-project/445 project 3/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/vivian/Documents/GitHub/Iat-445-final-project/445 project 3/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/vivian/Documents/GitHub/Iat-445-final-project/445 project 3/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
